### ISSUE TITLE
训练一开始时显示AssertError

### ISSUE THREAD

**Issue by ALLJISAN** [Liu-Yicheng/Faster-rcnn#6]
我用一张图片训练的时候是正常的，但是将全部图片写进train.txt和放到其他xml的文件夹时，显示AssertionError，我想请问一下这个error的情况

```
Called with args:
Namespace(batch_size=1, checkepoch=1, checkpoint=0, checkpoint_interval=10000, checksession=1, class_agnostic=True, cuda=True, disp_interval=1, large_scale=False, lr=0.001, lr_decay_gamma=0.5, lr_decay_step=50, max_epochs=500, num_workers=0, optimizer='adam', resume=False, save_epochs=500, session=1, start_epoch=1, use_tfboard=False)
Preparing training data
gt roidb loaded from /home/liangfeifan161_gmail_com/Faster-rcnn/Data/picture_data/cache/gt_roidb.pkl
Traceback (most recent call last):
  File "trainval_net.py", line 154, in <module>
    imdb, roidb, ratio_list, ratio_index = get_imdb_and_roidb('train')#'train'代表读取的是train.txt文件
  File "/home/liangfeifan161_gmail_com/Faster-rcnn/Data/pascal.py", line 81, in get_imdb_and_roidb
    roidb = get_roidb(imdb_set)
  File "/home/liangfeifan161_gmail_com/Faster-rcnn/Data/pascal.py", line 42, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/liangfeifan161_gmail_com/Faster-rcnn/Data/pascal.py", line 35, in get_training_roidb
    prepare_roidb(imdb)
  File "/home/liangfeifan161_gmail_com/Faster-rcnn/Data/pascal.py", line 27, in prepare_roidb
    assert all(max_classes[nonzero_inds] !=0)
AssertionError
```

**Comment by ALLJISAN** [comment]
我发train.txt文件里面写1行能够正常运行，2行或以上就报上面同样的错了，是哪个txt文件需要上面特定的保存格式吗？
